FROM python:3.11.2-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y install netcat gcc default-libmysqlclient-dev pkg-config \
    && apt-get clean

RUN pip install --upgrade pip && pip install uv
COPY ./requirements ./requirements
RUN uv pip install -r ./requirements/requirements.dev.txt --system

COPY . .

ENTRYPOINT [ "bash", "docker/api/migrate.sh" ]
